### PR TITLE
Code feature Added to Go Client

### PR DESCRIPTION
**Pull request by poojabaghelsendinblue**
Closing a channel has one more useful feature - reading operations on closed channels do not block and always return default value for a channel type
So Safe to close a Channel
Here the forever channel is only used to synchronize the execution but not for sending data.
As we close the channel in the goroutine the reading operation does not block and the main function continues to run.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@poojabaghelsendinblue Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=517)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=517) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@poojabaghelsendinblue Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=517)!

**Comment by michaelklishin** [comment]
Thank you. Please create a new branch off of `live` and re-submit.

**Comment by michaelklishin** [comment]
Related rabbitmq-tutorials PR: https://github.com/rabbitmq/rabbitmq-tutorials/pull/162.

**Comment by michaelklishin** [comment]
I've reviewed the code and here are my findings. The program in question waits for an interrupt (Ctrl+C) in order to finish. It is meant to continue running and consuming until that happens. The channel name hints at that, too. Assuming that I don't think that closing it will

 * Prevent any resource links
 * Produce any efficiency gains (the comment discusses potential blocking of operations)
 * Make any visible difference to the user

Thank you for your time and considering a contribution to the RabbitMQ ecosystem!

**Pull request closed without merging**
