### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by thanakritlee**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thanakritlee Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=695)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=695) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by lukebakken** [comment]
@thanakritlee please note that when you fix one tutorial, more than likely others have to be fixed, like I did in commit dc259fa6ef305f9fc99dd1b24c9cb235eb81a1f5

**Comment by thanakritlee** [comment]
@lukebakken right, my bad. Next time I'll also fix the other tutorials. Thanks for letting me know.

**Comment by lukebakken** [comment]
It's no problem! We appreciate people finding an error in one tutorial. It makes it easy to fix the others.

**Pull request merged**
