### PR TITLE
Node.js streams: add a tutorial on offset tracking

### PR DESCRIPTION
**Pull request by l4mby**
Tutorial 2 for RabbitMQ streaming nodejs client

### CODE REVIEW

**Comment by michaelklishin** [comment]
Executable version: https://github.com/rabbitmq/rabbitmq-tutorials/pull/445.

**Review by Gsantomaggio — CHANGES_REQUESTED** [review]
You need to link  the tutorial to the index file, here:
```
  <T2DiagramStreamToC/>
    * [Java](tutorials/tutorial-two-java-stream)
    * [C#](tutorials/tutorial-two-dotnet-stream)
    * [Go](tutorials/tutorial-two-go-stream)
    * [Python](tutorials/tutorial-two-python-stream)
    ```

Then you can try it locally to see the result.

thank you

**Comment by l4mby** [comment]
@Gsantomaggio i rebased and updated the index, do i have to also update the `sidebarsTutorials,js` ?

**Comment by Gsantomaggio** [comment]
@l4mby yes please.

**Review by Gsantomaggio — APPROVED** [review]

**Pull request merged**
