### PR TITLE
Update using-operator.md

### PR DESCRIPTION
**Pull request by aleksandarnasuovski**
Proposition to delete deployment insted of searching perf-test pod name.

### CODE REVIEW

**Comment by michaelklishin** [comment]
An earlier step in this guide creates a pod object, not a deployment one, so we cannot do this.

**Comment by pivotal-issuemaster** [comment]
@aleksandarnasuovski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1071)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1071) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@aleksandarnasuovski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1071)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1071) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
@pivotal-issuemaster this is an obvious fix

**Comment by pivotal-issuemaster** [comment]
@aleksandarnasuovski This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by aleksandarnasuovski** [comment]
@michaelklishin 
```
alex$ instance=rabbitmq
alex$ username=$(kubectl get secret ${instance}-rabbitmq-admin -o jsonpath="{.data.username}" | base64 --decode)
alex$ password=$(kubectl get secret ${instance}-rabbitmq-admin -o jsonpath="{.data.password}" | base64 --decode)
alex$ service=${instance}-rabbitmq-ingress
alex$ kubectl run perf-test --image=pivotalrabbitmq/perf-test -- --uri "amqp://${username}:${password}@${service}"
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/perf-test created
alex$ k get deploy
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
perf-test                   0/1     1            0           13s
rabbitmq-cluster-operator   1/1     1            1           12m
```

**Comment by Zerpet** [comment]
@aleksandarnasuovski 

The same command creates a Pod for me:

```bash
[...]
kubectl run perf-test --image=pivotalrabbitmq/perf-test -- --uri "amqp://${username}:${password}@${service}"
# pod/perf-test created
k get all -l run=perf-test
# NAME            READY   STATUS    RESTARTS   AGE
# pod/perf-test   1/1     Running   0          52s
```

No deployment object is created. I'm using `kubectl` 1.19.2.

**Pull request closed without merging**
