### PR TITLE
Update install-debian.md to correct debian mirrors

### PR DESCRIPTION
**Pull request by JoeAlamo**
The Debian Bookworm install steps had you adding mirrors for bullseye and the Debian Bullseye install steps had you adding mirrors for bookworm, I have switched these around.

### CODE REVIEW

**Comment by JoeAlamo** [comment]
@pivotal-cla This is an Obvious Fix

**Comment by michaelklishin** [comment]
@JoeAlamo you have updated the 4.x version of the website. Please backport these to `./versioned_docs/`. Thank you.

**Comment by JoeAlamo** [comment]
@michaelklishin didn't spot that, have changed 👍

**Comment by michaelklishin** [comment]
Thank you! Well spotted 👏

**Pull request merged**
