### PR TITLE
Fix second python tutorial

### PR DESCRIPTION
**Pull request by sazarkin**
New queue name is added in code example too early

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sazarkin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=448)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=448) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sazarkin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=448)!

**Comment by michaelklishin** [comment]
Thank you but I don't think I agree. The paragraph right above this snippet mentions a new program. In fact, I believe we had the proposed version, intentionally or not, at some point and it was seen as an issue by others.

**Comment by sazarkin** [comment]
Ok, it is up to you.
But there is issue, in tutorial text or code. 
Old program and this code snippet does not sync, and it looks like it was copy pasted from second half of this tutorial.
Cheers.

**Comment by uolot** [comment]
I came here to create the very same PR - this bit of example code doesn't match what the surrounding text suggests. 

Changing the `routing_key` is explicitly mentioned in the [Message durability](https://github.com/rabbitmq/rabbitmq-website/blob/live/site/tutorials/tutorial-two-python.md#message-durability) part of this tutorial:

> RabbitMQ doesn't allow you to redefine an existing queue with different parameters and will return an error to any program that tries to do that. But there is a quick workaround - let's declare a queue with different name, for example task_queue

Same for `delivery_mode`, a few lines down from the above:

> At that point we're sure that the task_queue queue won't be lost even if RabbitMQ restarts. Now we need to mark our messages as persistent
> * by supplying a delivery_mode property with a value 2.

Yet, these changes are introduced in the snippet that this PR tries to update. Doing the tutorial for the first time it's confusing and the PR should be accepted.

**Comment by michaelklishin** [comment]
Sentences prior to the modified example talk about modifying a tutorial 1 version which does not have additional message properties. Fair enough.

**Comment by michaelklishin** [comment]
Cherry-picked to `live` and it is already, well, live. Thank you.

**Pull request merged**
