### PR TITLE
Update dotnet docs for upcoming 7.0.0 release

### PR DESCRIPTION
**Pull request by lukebakken**
* Start by updating the client lib guide

Related: https://github.com/rabbitmq/rabbitmq-tutorials/pull/473

### CODE REVIEW

**Comment by michaelklishin** [comment]
@lukebakken should we mention at the top that the guide now covers v7.x of the client, and that there were certain API changes from 6.x?

**Comment by lukebakken** [comment]
> should we mention at the top that the guide now covers v7.x of the client, and that there were certain API changes from 6.x?

Feel free to add that, though these docs will go live the day that v7 ships, so presumably anyone reading them will create apps that use the new library version.

**Comment by lukebakken** [comment]
Note that the code references refer to this branch:

https://github.com/rabbitmq/rabbitmq-tutorials/tree/rabbitmq-dotnet-client-7.0.0

Once that branch is merged, this PR will be modified to use `main`

**Comment by lukebakken** [comment]
Thanks @michaelklishin

**Pull request merged**
