### PR TITLE
Remove duplicate from automatic recovery process

### PR DESCRIPTION
**Pull request by GitHubPang**
Remove duplicated point, "Restore connection listeners", from automatic recovery process.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@GitHubPang Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=993)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=993) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by GitHubPang** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@GitHubPang This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
