### PR TITLE
Fix typo from s to is

### PR DESCRIPTION
**Pull request by oneoneonepig**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@oneoneonepig Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=949)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=949) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@oneoneonepig Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=949)!

**Comment by lukebakken** [comment]
Thank you!

**Comment by michaelklishin** [comment]
The intent was likely to say "this includes".

**Pull request closed without merging**
