### PR TITLE
Stream tutorials

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Stream Tutorial

related to: https://github.com/rabbitmq/rabbitmq-tutorials/pull/382

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
@lukebakken @michaelklishin 
It's ready for review. For the moment, there is only the .NET part. I'd want to validate this before proceeding with other clients. 
Changes:
- Add the https://5bed5f5b.rabbitmq-website.pages.dev/tutorials#stream-tutorials 
- Header for the stream plugin https://5bed5f5b.rabbitmq-website.pages.dev/tutorials/tutorial-one-dotnet-stream#introduction
- Add the .NET getting started: https://5bed5f5b.rabbitmq-website.pages.dev/tutorials/tutorial-one-dotnet-stream#hello-world

**Comment by michaelklishin** [comment]
@Gsantomaggio I should get to this by the end of the week. But that should not prevent you from working on other stream tutorial ports (whatever they may be) :)

**Comment by Gsantomaggio** [comment]
Ok added [Go stream client](https://github.com/rabbitmq/rabbitmq-website/pull/1885/commits/d7b7b3068ba8739bfe309083eeb82133f1d40692) documentation here.


Add also the [Rust Source Code example](https://github.com/rabbitmq/rabbitmq-tutorials/pull/402)

**Comment by Gsantomaggio** [comment]
Added RUST documentation: https://f8023ae7.rabbitmq-website.pages.dev/tutorials/tutorial-one-rust-stream

**Comment by Gsantomaggio** [comment]
@michaelklishin @lukebakken ready for review. ( with a low priority :) )

**Comment by michaelklishin** [comment]
The forced push was a rebase.

**Comment by lukebakken** [comment]
Reviewing this today!

**Pull request merged**
