### PR TITLE
Add new page on monitoring with Prometheus

### PR DESCRIPTION
**Pull request by gerhard**
This covers the basics of monitoring with Prometheus.

@michaelklishin can you help with links to this page? monitoring is the obvious page to link from, but maybe you know of other website pages that should link to this page.

@deadtrickster I've captured in the guide when & why it's not enough to just run `rabbitmq-plugins enable prometheus_rabbitmq_exporter`. Is this something that you want to address?

### CODE REVIEW

**Comment by michaelklishin** [comment]
I will help with the edits later this week. We can link to this page from Developer Tools.

**Comment by michaelklishin** [comment]
This guide is written as a tutorial. That's not how our guides usually are, so the language has to be edited. The amount of hand holding this guide does seems somewhat excessive, too. It's a plugin installation tutorial and there's already a doc guide on plugins.

**Comment by michaelklishin** [comment]
@deadtrickster as explained in https://github.com/deadtrickster/prometheus_rabbitmq_exporter/issues/53, in 3.7.x apps that do not depend on `rabbit` will not show up on the plugin list. Enabling dependencies manually is wrong on many levels and if it's necessary, the plugin has to be fixed.

**Comment by deadtrickster** [comment]
ok, I finally got it and cared to check the app.src. Will fix

**Comment by gerhard** [comment]
This is the guide that I wish I had when starting out with Prometheus & RabbitMQ. It might feel repetitive and too "hand-holdy" in places, but it's self-contained and will work as expected on macOS, Linux and even Docker.

Please chop and trim as required, I'll be glad when a version of this will be helping others.

**Comment by deadtrickster** [comment]
should be fixed

**Comment by deadtrickster** [comment]
while prometheus_process_collector isn't mentioned, it's used by me and others. if it to be used plugins dir must be +x, perhaps worth mentioning this.

**Comment by gerhard** [comment]
@deadtrickster I've mentioned prometheus_process_collector, please feel free to add complete installation instruction on the plugin home page, https://github.com/deadtrickster/prometheus_process_collector

@michaelklishin happy with the last changes, OK to merge 👍

**Comment by michaelklishin** [comment]
@deadtrickster why is that? We can mention it but I wasn't going to mention that plugin if it's not essential.

**Comment by michaelklishin** [comment]
@gerhard I have more changes coming.

**Comment by deadtrickster** [comment]
@michaelklishin because it loads nifs.

**Pull request merged**
