### PR TITLE
Advanced mirrored queues configuration options

### PR DESCRIPTION
**Pull request by bogdando**
* Specify that the page consist of two parts:
 - A/P configuration and A/A with mirrored queues using Pacemaker OCF RA
* Describe the /usr/lib/ocf/resource.d/rabbitmq/set_rabbitmq_policy.sh
  file for advanced configuration of mirrored queues
* Do not use interleaved clones in examples as there is no need for that

Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

### CODE REVIEW

**Comment by bogdando** [comment]
WIP -1

**Comment by bogdando** [comment]
works for me now :)

**Comment by michaelklishin** [comment]
I assume this is for changes that will be in `3.5.7`? Then it needs to go into `stable` as we can't deploy it immediately.

**Comment by bogdando** [comment]
yes, ok

**Pull request closed without merging**
