### PR TITLE
Minor typo fixes

### PR DESCRIPTION
**Pull request by GitHubPang**
A few minor improvements in spelling, grammar, wording, punctuation, formatting, capitalization.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@GitHubPang Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1028)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1028) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by GitHubPang** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@GitHubPang This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by GitHubPang** [comment]
Can't proofread everything, but at least I can fix the easy ones.
I'll leave the hard ones to others. 🙂

**Pull request merged**
