### PR TITLE
Corrected some typos

### PR DESCRIPTION
**Pull request by ozkanb**
Corrected 2 typos in the upgrade documentation page

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ozkanb Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=824)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=824) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by ozkanb** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@ozkanb This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
