### PR TITLE
Typo fix in 2nd python tutorial

### PR DESCRIPTION
**Pull request by Birdi7**
Update the second tutorial on python. The correct name of the method is `basic_qos`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Birdi7 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=805)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=805) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by Birdi7** [comment]
It looks like I am messed with a method from AMQP 0-9-1 and a method in python, sorry

**Comment by pivotal-issuemaster** [comment]
@Birdi7 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=805)!

**Comment by pivotal-issuemaster** [comment]
@Birdi7 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=805)!

**Pull request closed without merging**
