### PR TITLE
fix RpcClient.cs code

### PR DESCRIPTION
**Pull request by naramdash**
1. delete weird semicolon
2. channel must be closed before closing connection (order is important)

code from [rabbitmq-tutorials > RPCClient.cs](https://github.com/rabbitmq/rabbitmq-tutorials/blob/main/dotnet/RPCClient/RPCClient.cs)

### CODE REVIEW

**Comment by naramdash** [comment]
if RpcClient is not disposed, Task from InvokeAsync will not completed.

**Comment by michaelklishin** [comment]
@naramdash channels do not have to be explicitly closed. When a connection is closed, so will be all channels on it.

**Comment by michaelklishin** [comment]
I will apply this change manually.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-website/commit/fbfd29818bd2d44de0ca344e470b62c0f627f299

**Pull request closed without merging**
