### PR TITLE
corrected the link of memory alarms

### PR DESCRIPTION
**Pull request by super1-chen**
corrected the link of memory alarms at queue.md

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@super1-chen Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=771)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=771) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@super1-chen Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=771)!

**Comment by pivotal-issuemaster** [comment]
@super1-chen Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=771)!

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
