### PR TITLE
Fixed a small typo.

### PR DESCRIPTION
**Pull request by mez**

### CODE REVIEW

**Comment by bdshroyer** [comment]
@mez Good catch, thanks! Would you mind submitting this PR against the `live` branch? The `master` branch doesn't get deployed until RabbitMQ 3.7.0 is release, and we'd like this fix on the current site.

**Comment by mez** [comment]
Ok, no problem!

**Comment by bdshroyer** [comment]
The change to `live` was merged in PR [#169](https://github.com/rabbitmq/rabbitmq-website/pull/169). Thanks for the pull request!

**Comment by michaelklishin** [comment]
Actually, queue name in tutorial 2 should be `"task_queue"`, that's what it is in other tutorials. If it's still `"hello"` somewhere else (e.g. in the code), we should fix that.

**Pull request merged**
