### PR TITLE
Minor typo fixes

### PR DESCRIPTION
**Pull request by GitHubPang**
A few minor fixes, such as typos and bad URL anchors.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@GitHubPang Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1008)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1008) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by GitHubPang** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@GitHubPang This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
