### PR TITLE
Updated tutorial six Java code examples due to QueueingConsumer deprecation

### PR DESCRIPTION
**Pull request by monosoul**

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thanks. Please submit this to rabbitmq/rabbitmq-tutorials first.

**Comment by monosoul** [comment]
@michaelklishin Done. But examples here and in rabbitmq/rabbitmq-tutorials are a bit out of sync.

**Comment by michaelklishin** [comment]
@monosoul a good chance to sync at least one up :) Stuff in rabbitmq-tutorials has taken a life of its own, contributors add tooling-specific or library-specific modifications there and a drift between the two repos naturally accumulates over time. We have to sync things up every so often. Future PRs in this area would be more than welcomed!

**Comment by monosoul** [comment]
@michaelklishin OK, I'll wait for my PR at rabbitmq-tutorials to be merged then. After that I'll sync changes with my rabbitmq-website branch.

**Comment by monosoul** [comment]
Closing in favor of #330 .

**Pull request closed without merging**
