### PR TITLE
Update heartbeats.md

### PR DESCRIPTION
**Pull request by cressie176**
See https://github.com/rabbitmq/rabbitmq-website/issues/1386

### CODE REVIEW

**Comment by lukebakken** [comment]
Thanks! I just copied the existing text in #1387. I'll let @michaelklishin decide which to use.

**Comment by michaelklishin** [comment]
Thank you. This suggestion makes practical sense: both sides should insist on disabling heartbeats for best predictability.

FTR, here is the server function that performs negotiations of values such as the heartbeat timeout and
`channel_max`: https://github.com/rabbitmq/rabbitmq-server/blob/v3.10.x/deps/rabbit/src/rabbit_reader.erl#L1349-L1358.

**Comment by lukebakken** [comment]
Perfect. I figured that you would have suggestions.

**Comment by michaelklishin** [comment]
Thank you, @cressie176

**Pull request merged**
