### PR TITLE
Updating based on conversation in pull request

### PR DESCRIPTION
**Pull request by chaitanyagurrapu**

### CODE REVIEW

**Comment by chaitanyagurrapu** [comment]
Will try to find the cycles to make the changes to the other language tutorials.

Not sure what you mean by point 1 though. Should I just add the above link at the end of the paragraph?

I will read the link above and finish the tutorials and maybe it will all make sense.

**Comment by michaelklishin** [comment]
I mean that "automatic mode" could be "[automatic mode](http://www.rabbitmq.com/confirms.html)" :) thank you!

**Comment by michaelklishin** [comment]
I will apply this manually to all tutorials. Thank you.

**Comment by michaelklishin** [comment]
Actually, this cannot be applied to all tutorials because the default is not the same in all client libraries. I will revisit them one by one.

**Pull request closed without merging**
