### PR TITLE
Auto-configuration of a cluster with a Pacemaker

### PR DESCRIPTION
**Pull request by bogdando**
Describe how to use the shipped OCF script for a
Pacemaker resource agent to configure an A/A cluster
with dynamic nodes' membership.

Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
The reason why this is not merged: I think this belongs to the Pacemaker guide, will move it there and adapt accordingly soon.

**Comment by bogdando** [comment]
Okay, thank you. Waiting for updates then.

**Comment by michaelklishin** [comment]
@bogdando [this is live](http://www.rabbitmq.com/pacemaker.html) now. Thank you again.

**Pull request merged**
