### PR TITLE
[devtools] Add aioamqp (Python)

### PR DESCRIPTION
**Pull request by michael-k**
https://github.com/Polyconseil/aioamqp

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@michael-k Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=594)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=594) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
The client seems to have a differentiating feature (built on a new-ish Python I/O framework) and sensible API according to the tutorials. @lukebakken any objections to listing it?

**Comment by michaelklishin** [comment]
@michael-k thank you. We only add new clients and tool after some discussion on the team, so this may take some time.

**Comment by pivotal-issuemaster** [comment]
@michael-k Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=594)!

**Comment by lukebakken** [comment]
Looks like something we should include. Thanks!

**Pull request merged**
