### PR TITLE
oauth2 scope documentation/typo fix

### PR DESCRIPTION
**Pull request by m1schka-bdr**
match the scope code with the written documentation

### CODE REVIEW

**Comment by m1schka-bdr** [comment]
thinking about it again, it could also be that it was correct (at this position) but then it´s wrong at line 367
let me know

**Comment by michaelklishin** [comment]
It should be `x-*` for exchange name, since the section is dedicated to topic permissions (which only apply to topic exchanges).

Thank you.

**Comment by m1schka-bdr** [comment]
but then, as I corrected myself, everything should start with `x-`. should I provide another PR or do you want to leave it as it is right now?

**Comment by m1schka-bdr** [comment]
nevermind, I just saw you corrected it in a follow up commit. thx

**Pull request merged**
