### PR TITLE
Fix component in erlang repository

### PR DESCRIPTION
**Pull request by sagikazarmark**
IMHO this is an Obvious Fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sagikazarmark Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=681)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=681) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sagikazarmark This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by sagikazarmark** [comment]
Breaking Travis seems unrelated?

**Comment by michaelklishin** [comment]
There is no CI for this repo although at some point there was an attempt, so I disabled PR checks.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
