### PR TITLE
Initial instructions for AMQP 0-9-1 dissection using Wireshark 2.0.

### PR DESCRIPTION
**Pull request by gotthardp**
Wireshark 2.0rc1 is scheduled for Oct 14 and the final release tentatively for Nov 18. Once rc1 is out I will announce this on the rabbitmq-user list and ask for thorough testing, so I thought it may be useful to describe its features (i.e. "what to expect"). I wrote it in a form of a website, but I leave it entirely up to you if and how it should be included.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

Should we link to this page from the [navigation tree](https://github.com/rabbitmq/rabbitmq-website/blob/master/site/pages.xml.dat)?

**Comment by gotthardp** [comment]
Probably yes and I can add the links, I was just not sure from where. The community section? The protocol section?

**Comment by michaelklishin** [comment]
The protocol section makes most sense to me. It can also go next to the tooling pages (2 links to a single page from relevant sections is OK).

**Comment by gotthardp** [comment]
I added the two links.

**Comment by michaelklishin** [comment]
:+1:

**Comment by michaelklishin** [comment]
This is submitted against master. Can you rebase if needed and submit against live? Then we can publish it today. master is for 3.6.0-specific stuff.

**Comment by gotthardp** [comment]
OK, I need to resubmit.

**Pull request closed without merging**
