### PR TITLE
Fix grammar error in access-control.md

### PR DESCRIPTION
**Pull request by staa99**
'to connecting to it' should be 'to connect to it'

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@staa99 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1021)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1021) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by staa99** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@staa99 This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by acogoluegnes** [comment]
Thanks!

**Comment by staa99** [comment]
It's my pleasure 🙂

**Pull request merged**
