### PR TITLE
Fix premature ack in tutorial

### PR DESCRIPTION
**Pull request by raedwa01**
Ack in first block of code causes error because of noAck = true.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@raedwa01 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=772)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=772) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
FTR, the example in question uses automatic acknowledgements because manual acknowledgement is introduced [later in the tutorial](https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html). So this solution is the right one. Thank you.

**Comment by pivotal-issuemaster** [comment]
@raedwa01 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=772)!

**Comment by raedwa01** [comment]
I agree it is introduced later, it was that the noAck being true at that point in the tutorial caused an error to throw.  Once i got lower in the tutorial and ran under that updated code, with noAck = false, it ran fine.

**Pull request merged**
