### PR TITLE
Revamp the rabbitmq.com home page

### PR DESCRIPTION
**Pull request by dumbbell**
> The initial pull request (#1813) was merged into `main` too early as this work is still in its early stage of development. I reverted the merge and resubmitted the branch in this new pull request. The message below is the original description from @pstack2021.
> — @dumbbell

Updates to the RabbitMQ homepage, these changes were agreed on in a meeting this morning (27.02.2024) with product management @HowardTwine and @DigitalBlasco and with development @dumbbell and @mkuratczyk 

Doc tracking these changes: https://docs.google.com/document/d/1j7P4aM1IJFnl0E3InMVYk83g9ggOqwWDdT1DJKQHqxI/edit#heading=h.x02o23co6ze2

**Points to note:**
 - I haven't done anything with the banners, we can just leave the ones that are there for now. As agreed this morning, the plan is to create a 3.13 blog and when published, use this as a banner on the home page. 
 
 @dumbbell @mkuratczyk - Is there anyone that can write this blog for us? I can review it. I need to concentrate on writing the Introductory and other topics for the new OSS RMQ site (so we can publish the TOC I have built soon) and then get back to the commercial RabbitMQ 1.6 docs as these releases will be coming soon, thanks.

### CODE REVIEW

**Comment by mkuratczyk** [comment]
I can write the blog post if there are no other volunteers

**Comment by dumbbell** [comment]
@mkuratczyk: Feel free to write it :-) Otherwise I will do it once I'm done with the homepage.

**Comment by pstack2021** [comment]
Thanks @mkuratczyk. If you could write the blog post that would be great. Can we make this blog for all users please. Currently RabbitMQ release notes are aimed at more of a developer type audience rather than for other personas such as administrators. If we can keep descriptions simplistic yet with enough detail that all users "just get it". I do understand that the release notes are more "change log" type material hence written in this way

As an example of what I mean, please take a look at the items under "Core Broker" in the 3.12.12 release notes: https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.12.12, then compare these descriptions to those in the commercial release notes: https://docs.vmware.com/en/VMware-RabbitMQ-for-Kubernetes/1/rmq/release-notes.html (see under Core Server: Bug Fixes), I can review the blog PR when it is ready. 

Many thanks
Paula

**Comment by pstack2021** [comment]
Another example for you to reference @mkuratczyk, please see the MQTT plugin bug fix description in the [3.12.12 release notes ](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.12.12) and then compare it with my description (search for: Allow MQTT QoS 0 subscribers to reconnect) in the [VMware RabbitMQ for K8s release notes](https://docs.vmware.com/en/VMware-RabbitMQ-for-Kubernetes/1/rmq/release-notes.html).

**Comment by pstack2021** [comment]
Hi @dumbbell,

Firstly, let me commend you on the brilliant job you have done with the RabbitMQ homepage, I think it looks great and it will be liked for users of all types: new and old. I love the tabs for the use cases, so easy to see each one at a glance and move between them. 

I am providing feedback here rather than sequencing through all the commits, I hope this is ok:

1. Remove full stop at the end of the one liner at the top of the page i.e. change it to: **One broker to queue them all** I know the https://www.rust-lang.org/ site uses it but if you search open source software sites in general most of them don't have, I think it looks better without it.
2. How about adding this to the introductory sentence to give it additional power/immediately tell users how many are using it already, can we change: _RabbitMQ is a reliable and mature messaging and streaming broker, which is easy to deploy on cloud environments, on-premises, and on your local machine._ to _RabbitMQ is a reliable, mature messaging and streaming broker, which is easy to deploy on cloud environments, on-premises, and on your local machine. It is currently used by millions worldwide._
3. Under the **Interoperable** heading, possibly change: _There is certainly a client library available for the programming language you love. No vendor lock-in!_ to  _There are multiple client library available, which can be used with your programming language of choice, just pick one. No vendor lock-in!_ 
4. Under **Flexible**, heading, I would change the word "etc: to "and so on", I wouldn't use word abbreviation in a home page or anywhere in documentation really. 
5. Under **Reliable** heading, in this sentence change "be sure" to "ensure"
6. Under Examples of common use cases, suggested minor rewrite for this text: _Here is a selection of common use cases we hear about from the community or the customers. You may find yourself in one of these cases and RabbitMQ can definitely help! Of course RabbitMQ is useful in many more situations._ can we change this to: _Here is a few common use cases we hear about from the community and our customers. If you find yourself in one of these cases, RabbitMQ is definitely the message and streaming broker that can help! We cannot provide all our use cases here, RabbitMQ can be used in many more situations, For help, contact the RabbitMQ team using the various contact methods at the end of this page._
7. RPC use case example: Possibly change: _The website or kiosk expects to get an answer for the order in no time._ to _The website or kiosk expect to get an answer for the order in minimal time._
8. Minor grammatical update, highlighted in bold:  _The caller that pushed the order then subscribes to another queue and wait for an answer with that same correlation ID._ to _The caller that pushed the order then subscribe**s** to another queue and wait**s** for an answer with that same correlation ID_.
9. RPC use case example: Minor rewrite, possibly change: _A [classic queue](https://8cddb8b8.rabbitmq-website.pages.dev/docs/classic-queues) is a good fit here to achieve lower latency, at the expense of less safety — the caller can still retry. If however the order cannot be lost, you should prefer the combination of [acknowledgments](https://8cddb8b8.rabbitmq-website.pages.dev/docs/confirms) and [quorum queues](https://8cddb8b8.rabbitmq-website.pages.dev/docs/quorum-queues) to ensure a message is safe once confirmed. to: _To achieve lower latency, a [classic queue](https://8cddb8b8.rabbitmq-website.pages.dev/docs/classic-queues) is a good fit here but it is at the  the expense of less safety — the caller can still retry. However, if the order cannot be lost, you might prefer to use a combination of [acknowledgments](https://8cddb8b8.rabbitmq-website.pages.dev/docs/confirms) and [quorum queues](https://8cddb8b8.rabbitmq-website.pages.dev/docs/quorum-queues) to ensure a message is safe once confirmed._

_the caller can still retry_ does this text fit right at its location above?

10. RPC use case example: To improve readability, minor rewrite: _This topology allows to serialize the processing of orders to serve them in a first come first served order. This avoids the need for transactions._ to: _This topology allows the processing of orders to be serialized to serve them in a first come first served order. This avoids the need for transactions._ 

11. Streaming use case example: suggested rewrite in the 1st paragraph - change: _You run a video platform. When a user upload a new video, you have a ton of things to do once the video was safely stored: run some post-upload analysis, transcode lower quality copies of the video, notify other users subscribed to the author's creations, …_ to _You run a video platform. When a user uploads a new video, you have multiple tasks to complete when the video is safely stored: run some post-upload analysis, transcode lower quality copies of the video, notify other users subscribed to the author's creations, and so on._ 
12. IoT use case example: 

To be continued @dumbbell, I need to log off now for a while

**Comment by dumbbell** [comment]
Thank you @pstack2021 for the extensive review!

I applied all your suggestions, except the following ones:

> Here is a few common use cases we hear about from the community and our customers. If you find yourself using one of these cases, RabbitMQ is definitely the message and streaming broker that can help! We cannot provide all our use cases here, RabbitMQ can be used in many situations. For more information, contact the RabbitMQ team using the various contact methods at the end of this page.

I agree the paragraph I wrote must be improved (I didn't have inspiration). However, we can't tell people to specifically ask us: this is a FOSS and they should ask the community (which we are part of). For a dedicated channel with the RabbitMQ team, this is commercial support territory.

> the caller can still retry does this text fit right at its location above?

Can you clarify?

> What about the License section: what exactly does "Behind the scene, RabbitMQ backed by Broadcom who offer professional services." mean?? "what professional services?

I didn't change the paragraph yet. We mostly need to paragraph to introduce the two sections below (FOSS and commercial offerings) and act as a horizontal visual delimiter. Like the one above, I didn't have inspiration. Most of the actual content should go in the sections below.

> Also in addition to this paragraph, I would include information about how customers can contribute how about adding an additional paragraph similar to the following:

I didn't put this entire paragraph because this is not the place to explain how to contribute, I believe. I just put "Take a look at our Contributors page." with the link. What do you think?

> In addition, a commercial edition of RabbitMQ is available which comes with exclusive warm standby replication and intra-cluster data compression advanced features

In this suggestion, I re-introduced the "such as" part because we may add other features in the future and we shouldn't have to list them all here.

> Also for the list under this heading are they listed in the order that we want users to contact us i.e. do we want to direct people to slack first??

Good idea, I put GitHub first. However, no, Slack should stay last. The mailing-list and Discord are the preferred channels, because it's too cumbersome to invite people to Slack.

I added Twitter but I don't consider it a communication platform. This is probably the worst way to contact us. As the platform name tells it, it's mostly noise.

**Pull request merged**
