### PR TITLE
WIP Important cluster metrics to monitor

### PR DESCRIPTION
**Pull request by gerhard**
This question came up recently, we wanted to add it to the metrics docs.

It's still WIP, but we wanted to share it early so that we can discuss.

### CODE REVIEW

**Comment by lukebakken** [comment]
I'll keep my eye on this, thanks.

**Comment by michaelklishin** [comment]
Cluster links (partitions) and alarms are also "top" in my books. Can we change this to "important metrics" since this is not a competition? :)

**Comment by gerhard** [comment]
The exact question was **Which are the top 5 RabbitMQ metrics that we should monitor?**, and I instantly though **If you can only monitor 5 metrics about your RabbitMQ Clusters, these should be it**, to the [Everybody's Free To Wear Sunscreen](https://www.youtube.com/watch?v=sTJ7AzBIJoI) tune.

Partitions and alarms are essential checks, but are they metrics? For example, partitions would be addressed by the first metric: **This metric needs to be collected from each node so that we can be confident that each node is able to communicate with every other node.**. Alarms would be addressed by the most important node metrics (separate PR maybe?): Erlang run queue, memory, disk, file descriptors & socket descriptors.

**Comment by michaelklishin** [comment]
The presence of certain things can be thought of as a boolean gauge but fair enough.

**Comment by michaelklishin** [comment]
Closing per discussion with @gerhard. This PR has been superseded by monitoring guide and toolchain updates in `live`.

**Pull request closed without merging**
