### PR TITLE
Fixed wrong link.

### PR DESCRIPTION
**Pull request by a2n**
Fixed wrong link.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@a2n Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=793)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=793) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by a2n** [comment]
@pivotal-issuemaster Hey, this is a [obvious fix](https://cla.pivotal.io/about#obvious-fixes), no need to sign.

**Comment by pivotal-issuemaster** [comment]
@a2n This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
