### PR TITLE
Fix typos and add clarification to delivery ack docs

### PR DESCRIPTION
**Pull request by ekatpat**
- Remove typos and clarify wording
- Add instruction on how to resolve a `PRECONDITION_FAILED` channel exception

### CODE REVIEW

**Comment by michaelklishin** [comment]
@pivotal-cla this is a trivial fix

**Comment by michaelklishin** [comment]
This only updates the 4.0.x version of the docs.

**Comment by michaelklishin** [comment]
@ekatpat thank you. I will update 4.1 and 3.13 versions of this section on your behalf.

**Comment by ekatpat** [comment]
Thank you @michaelklishin

**Pull request merged**
