### PR TITLE
Add Brighter to list of .NET Client Libraries and Developer Tools

### PR DESCRIPTION
**Pull request by iancooper**
A simple change to add Brighter to the list of .NET Client libraries for RabbitMQ

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@iancooper Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=836)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=836) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@iancooper Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=836)!

**Comment by michaelklishin** [comment]
@iancooper thank you. I took the liberty of editing your project description. We generally add projects we see in the wild to this list but Brighter seems well documented, which is a huge selling point if you ask me.

**Comment by michaelklishin** [comment]
By the way, please announce Brighter on the rabbitmq-users mailing list.

**Comment by iancooper** [comment]
Thanks, good suggestion

**Pull request merged**
