### PR TITLE
Spring tutorials are missing an @EnableScheduling annotation

### PR DESCRIPTION
**Pull request by vicianm**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@vicianm Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=778)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=778) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vicianm Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=778)!

**Comment by michaelklishin** [comment]
@acogoluegnes @garyrussell perhaps you folks understand the intent here?

**Comment by vicianm** [comment]
Quote from https://spring.io/guides/gs/scheduling-tasks/:

    @EnableScheduling ensures that a background task executor is created. Without it, nothing gets scheduled.

It's possible that the @EnableScheduling annotation is necessary on other than the 3 aforementioned tutorials. So far I tested only on these. Without the annotation no TutNSender#send() method gets fired.

**Comment by michaelklishin** [comment]
Looks like it is because publishers in all 6 Spring tutorials rely on `@Scheduled` for periodic task execution. Why are we only updating 3 tutorials then and not all of them? Only tutorial 1 at the moment
uses `@EnableScheduling`:

```
grep -R "EnableScheduling" site
site/tutorials/tutorial-one-spring-amqp.md:import org.springframework.scheduling.annotation.EnableScheduling;
site/tutorials/tutorial-one-spring-amqp.md:@EnableScheduling
```

**Comment by vicianm** [comment]
**Why am I updating only 3 tutorials?**
As I already mentioned, because so far I didn't test the rest of them. I tested only the first three tutorials. If rest of the tutorials also rely on `@Scheduled` the `@EnableScheduling` should be probably added.

**Why the tutorial might work for somebody?**
The one who doesn't need explicit `@EnableScheduling` declaration might have declared the annotation implicitly in some dependency (see for example this link: https://stackoverflow.com/questions/43204377/spring-boot-scheduler-runs-without-enablescheduling-annotation)

**Comment by garyrussell** [comment]
`@EnableScheduling` only needs to be on one configuration class.

It is already there on the `RabbitAmqpTutorialsApplication` class further down in the tutorial.

https://github.com/rabbitmq/rabbitmq-website/blame/live/site/tutorials/tutorial-one-spring-amqp.md#L149

**Comment by vicianm** [comment]
> `@EnableScheduling` only needs to be on one configuration class.
> 
> It is already there on the `RabbitAmqpTutorialsApplication` class further down in the tutorial.
> 
> https://github.com/rabbitmq/rabbitmq-website/blame/live/site/tutorials/tutorial-one-spring-amqp.md#L149

I see. My bad.

I generated the project with Spring's Initializr (https://start.spring.io/) and did not copy the whole content from you tutorial.

**Comment by michaelklishin** [comment]
Thank you @garyrussell 👏.

**Pull request closed without merging**
