### PR TITLE
Fixed description of AMQP protocol.

### PR DESCRIPTION
**Pull request by zmej-serow**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@zmej-serow Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=773)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=773) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@zmej-serow Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=773)!

**Comment by michaelklishin** [comment]
Honestly, I don't know how "general-purpose" is defined in this context but that's definitely true if you ask me and the sentence now reads better. Thank you.

**Comment by zmej-serow** [comment]
I've just copied the description from Java tutorial section, where it _does_ fit the rules of language. My pleasure.

**Pull request merged**
