### PR TITLE
Add missing verb

### PR DESCRIPTION
**Pull request by ThomasVuillaume**
Just fix minor typo

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ThomasVuillaume Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=920)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=920) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ThomasVuillaume Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=920)!

**Comment by michaelklishin** [comment]
Thank you!

**Comment by ThomasVuillaume** [comment]
My pleasure ;)

**Pull request merged**
