### PR TITLE
Typo in confirms.xml: ndoes -> nodes

### PR DESCRIPTION
**Pull request by tmszdmsk**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tmszdmsk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=496)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=496) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tmszdmsk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=496)!

**Comment by michaelklishin** [comment]
Thank you!

**Comment by tmszdmsk** [comment]
👍

**Pull request merged**
