### PR TITLE
Update amqp-0-9-1-quickref.css

### PR DESCRIPTION
**Pull request by SudershanSharma**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@SudershanSharma Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1067)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1067) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@SudershanSharma Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1067)!

**Comment by michaelklishin** [comment]
Would you mind explaining what this comment is meant to improve?

**Comment by michaelklishin** [comment]
This is a Hacktoberfest PR spam as far as we can tell. Reporting as such.

**Pull request closed without merging**
