### PR TITLE
 Bootstrapping the pip installer

### PR DESCRIPTION
**Pull request by 4383**
Prefer to use ensurepip instead of the deprecated easy_install

### CODE REVIEW

**Comment by michaelklishin** [comment]
According to [this guide](https://docs.python.org/3/library/ensurepip.html), `ensurepip` ships with Python 3.4+. I think it's a good idea to keep the tutorials compatible with earlier versions. I will revert https://github.com/rabbitmq/rabbitmq-tutorials/pull/232/files.

@4383 thank you for your time, though. Our team has learned something about `pip` bootstrapping today :)

**Comment by 4383** [comment]
`ensurepip` work with python 2.7 too => https://docs.python.org/2.7/library/ensurepip.html

**Comment by 4383** [comment]
See => https://www.python.org/dev/peps/pep-0477/

**Comment by 4383** [comment]
@michaelklishin @lukebakken normally `ensurepip` work with all the python version and `easy_install` is deprecated and will be removed soon, so I think it's more secure now to use `ensurepip` rather than `easy_install` 

https://setuptools.readthedocs.io/en/latest/easy_install.html

**Comment by lukebakken** [comment]
We could mention `ensurepip`, but it's not always available.

```
C:\Users\lbakken
> which pip
C:\Python37\Scripts\pip.exe
C:\Users\lbakken
> which ensurepip
Not found
```

I don't really think it's our job to inform users how to install Python modules.

**Comment by michaelklishin** [comment]
I don't have `ensurepip` in my 3.7 installation on macOS either (provisioned via Homebrew).

**Pull request closed without merging**
