### PR TITLE
Add remark about no default user created when importing definitions i…

### PR DESCRIPTION
**Pull request by databu**
…n blank node

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you but we would not recommend anyone who imports definitions to use the default user.

On top of that, the same fact is already mentioned [in the Definitions guide](https://rabbitmq.com/definitions.html#import-on-boot).

**Comment by databu** [comment]
As I mentioned, we're using this only in testing. It took me several days of debugging and research until I found this notice in the definitions doc. Please consider accepting the PR when I either:
1. add your remark that using a default user with imported definitions is not recommended, or
2. removing the guest user example.

**Comment by michaelklishin** [comment]
@databu from the [Access Control](https://rabbitmq.com/access-control.html#default-state) guide:

> It is advisable to [pre-configure a new user with a generated username and password](https://rabbitmq.com/access-control.html#seeding) or [delete](https://rabbitmq.com/rabbitmqctl.8.html#delete_user) the guest user or at least [change its password](https://rabbitmq.com/rabbitmqctl.8.html#change_password) to reasonably secure generated value that won't be known to the public.

I'm not sure what example you are referring to.

**Comment by databu** [comment]
The example that I had added in my PR. Again, I'm talking about a test system and the fact that it took me days to find out the issue. Because I was looking at the access control doc, which has no indication that importing definitions doesn't create the default user. This was also different in older releases. I didn't think of looking in the definitions doc because that just didn't occur to me. 
Shall we continue this discussion in [the issue](https://github.com/rabbitmq/rabbitmq-website/issues/1608) instead?

**Pull request closed without merging**
