### PR TITLE
Update the example code

### PR DESCRIPTION
**Pull request by slim-hmidi**
In order to understand more when learning RabbitMQ, we could enhance the variables' names to get a clear vision about different element and the relation between them.
So, instead of declaring `q` we could name it `queue` which is more expressive and helps a person to get the info and understand the principle faster.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@slim-hmidi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=743)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=743) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@slim-hmidi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=743)!

**Comment by michaelklishin** [comment]
Thank you for your time. I don't think we have seen this brought up before (with thousands of page views for each tutorial a month), and going from `q` to `queue` really isn't much of an improvement. What really helps with understanding is [a protocol overview document](https://www.rabbitmq.com/tutorials/amqp-concepts.html) and the rest of the docs.

However, other tutorials use `connection` and `queue`, so perhaps it's worth doing. Please update the [executable version](https://github.com/rabbitmq/rabbitmq-tutorials/tree/master/javascript-nodejs) first.

**Comment by slim-hmidi** [comment]
@michaelklishin  I know that does not clarify the concept of the protocol. However, when we use a single characters in naming variables could block the process of understanding things if the example will be long.

**Comment by michaelklishin** [comment]
These tutorials are not long and `conn`, `ch`, `q` are not unreasonable names in this specific case. Anyhow, I'm open to renaming but we have to update the runnable version first.

**Comment by lukebakken** [comment]
Please see rabbitmq/rabbitmq-tutorials#220. Once that is merged, this PR can be updated to reflect the code changes from there. Thanks.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-tutorials/pull/220 is in.

**Comment by michaelklishin** [comment]
@slim-hmidi would you like to sync this PR with https://github.com/rabbitmq/rabbitmq-tutorials/pull/220 or should we do it?

**Comment by slim-hmidi** [comment]
I will sync it.

**Comment by slim-hmidi** [comment]
@michaelklishin I synchronized the PR could you check it?

**Comment by michaelklishin** [comment]
Looks reasonable, thank you 👍

**Pull request merged**
