### PR TITLE
4.x: add AMQP address v2

### PR DESCRIPTION
**Pull request by ansd**
This is the documentation for https://github.com/rabbitmq/rabbitmq-server/pull/10873

### CODE REVIEW

**Comment by dumbbell** [comment]
We will be able to review and merge this patch after #1878 which creates the 3.13 docs folder.

**Comment by dumbbell** [comment]
The 3.13 docs were branched (#1878). Therefore, this pull request can be rebased, reviewed and merged.

**Comment by dumbbell** [comment]
@ansd: I don’t know if it was intentional, but the page added by this pull request is not linked by another page or a sidebar. Therefore it can only be reached by search or by typing the URL. Is it on purpose?

**Comment by ansd** [comment]
@dumbbell I would like to add the new page to the sidebar. My hope was that this gets done automatically. It looks like I have to manually add the new page to https://github.com/rabbitmq/rabbitmq-website/blob/main/sidebarsDocs.js?

**Comment by dumbbell** [comment]
Indeed, the ToC is edited manually to get the order, hierarchy and labels right.

`sidebarDocs.js` is the correct file to edit. It is divided to target two types of users:
* Developers under "How to Use RabbitMQ"
* Admins under "How to Manage RabbitMQ" (and "How to Monitor RabbitMQ")

**Comment by ansd** [comment]
Thanks for spotting this. I added the new page to the sidebar: https://github.com/rabbitmq/rabbitmq-website/commit/1942ef9da56a746658ea47b44a5dbd5231c50d0f

**Pull request merged**
