### PR TITLE
corrId is accessed from within inner class

### PR DESCRIPTION
**Pull request by gevorg**
java: local variable corrId is accessed from within inner class; needs to be declared final

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gevorg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=504)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=504) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gevorg Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=504)!

**Comment by michaelklishin** [comment]
Thank you!. May I ask you to submit the same change to the [runnable version](https://github.com/rabbitmq/rabbitmq-tutorials)? :)

**Comment by gevorg** [comment]
@michaelklishin done already ;)

**Comment by michaelklishin** [comment]
Doh, I missed the notification somehow. Thanks again!

**Pull request merged**
