### PR TITLE
"uris" parameter should be "brokers"

### PR DESCRIPTION
**Pull request by schmaxit**
see [advanced config example](https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.3/docs/advanced.config.example)

### CODE REVIEW

**Comment by michaelklishin** [comment]
I'd look at [the source](https://github.com/rabbitmq/rabbitmq-shovel/blob/bf82a200c1d422a3fbf1020758726f9486967512/src/rabbit_shovel_config.erl#L31) but your observation seems to be correct.

**Comment by pivotal-issuemaster** [comment]
@schmaxit Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=964)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=964) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
Thank you!

**Comment by pivotal-issuemaster** [comment]
@schmaxit Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=964)!

**Pull request merged**
