### PR TITLE
partially fix rabbitmq-diagnostics cipher_suites

### PR DESCRIPTION
**Pull request by metas-ts**
I'm confident in the fix at line 1344, 1347 ad 1355..
But I don't know what would be the correct fix at line 1373.
Pls advise

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@metas-ts Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1123)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1123) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@metas-ts Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1123)!

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
The example on line 1373 is now redundant: `--format erlang` does the same thing in 3.8.

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
I've removed the duplicate example in `live`.

**Pull request merged**
