### PR TITLE
Mention new ways of setting Consumer Timeout

### PR DESCRIPTION
**Pull request by ikvmw**
see  #5437

### CODE REVIEW

**Review by michaelklishin — CHANGES_REQUESTED** [review]
We cannot provide an Erlang consumer example and assume that would be enough. We can provide Java and .NET examples, and perhaps a Python one, and leave it at that.

**Review by johanrhodin — CHANGES_REQUESTED** [review]
`In the recent RabbitMQ versions` -> `In recent RabbitMQ versions`

BUT I'd prefer if it said more explicitly which version(s) (`3.10.x`, `3.11.y`) it was introduced in since a 9 months from now we don't know what "recent" was in April 2023.

**Comment by michaelklishin** [comment]
@johanrhodin that's what change logs are for. We usually remove specific version mentions in a year or so.

**Review by michaelklishin — COMMENTED** [review]
This fails to render because `<` and `>` must be escaped.

**Pull request merged**
