### PR TITLE
Switch website from home-grown framework to Docusaurus 3

### PR DESCRIPTION
**Pull request by dumbbell**
## Why

We want to modernize our website and include the documentation for multiple versions of RabbitMQ. This is critical with RabbitMQ 4.0 release on approach where several features will be removed. If we serve the latest version of the docs only, people looking for information about things such as classic mirrored queues won't find anything, even though RabbitMQ 3.x will still be supported for months.

## How

After evaluating several solution, we settled on Docusaurus 3 because:
* It handles docs versioning natively.
* It uses Markdown as the main markup language while still allowing more advanced pages with HTML and JSX/MDX.
* It supports Algolia for the internal search. The index is aware of versions so if you search for e.g. quorum queues, it only returns results from the currently viewed version of RabbitMQ, not all of them.

It also brings several benefits over the previous home-grown framework:
* It includes a blog so we have everything in one place and can easily reference pages between the blog and the docs. The Algolia internal search also covers the blog; something we don't have currently because we use two difference websites for the docs and the blog.
* It supports small screens (mobile).
* It supports a dark theme.

Blog snapshot: rabbitmq/rabbitmq-blog@cf2672ed5ef2af86b153ed235091b1b7c83ede6b.

This upgrade was announced on the RabbitMQ blog:
https://blog.rabbitmq.com/posts/2024/01/new-website/

The testing website is published at the following URL:
https://rabbitmq-website.pages.dev/

### CODE REVIEW

**Comment by henrikrxn** [comment]
Think I found a couple of doc links that have not been updated

# Section in docs

https://rabbitmq-website.pages.dev/docs/admin-guide#authentication-and-authorisation

## 404 links

- [OAuth 2 Support](https://rabbitmq.com/oauth2)
  should be 
  [OAuth 2 Support](https://rabbitmq-website.pages.dev/docs/oauth2)
- [OAuth 2 Examples](https://rabbitmq.com/oauth2-examples) for common identity providers
  should be
   [OAuth 2 Examples](https://rabbitmq-website.pages.dev/docs/oauth2-examples) for common identity providers

**Comment by michaelklishin** [comment]
@henrikrxn thank you for helping us test this "release" 👏

**Comment by dumbbell** [comment]
>     * [OAuth 2 Support](https://rabbitmq.com/oauth2)
>       should be
>       [OAuth 2 Support](https://rabbitmq-website.pages.dev/docs/oauth2)
> 
>     * [OAuth 2 Examples](https://rabbitmq.com/oauth2-examples) for common identity providers
>       should be
>       [OAuth 2 Examples](https://rabbitmq-website.pages.dev/docs/oauth2-examples) for common identity providers

Indeed, good catch!

The links in the master branch are hardcoded to use "https://rabbitmq.com" which is incorrect and won't work anymore once the current website move to another domain. My link conversion script didn't pick these up.

Thank you :)

I just pushed a fix to `main` and rebased this branch on top of it. It should be published a 5-6 minutes.

**Comment by dumbbell** [comment]
Someone reported out-of-band that the homepage was not rendered properly on small screens. This should be fixed now.

**Comment by dumbbell** [comment]
This fixes #1692.

**Pull request merged**
