### PR TITLE
fix ttl.md typo in word 'publish'

### PR DESCRIPTION
**Pull request by KristobalJunta**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@KristobalJunta Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=820)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=820) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by KristobalJunta** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@KristobalJunta This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
