### PR TITLE
Clarify what happens after setting TTL policy

### PR DESCRIPTION
**Pull request by binarin**
To make it clear that server resources will be freed, and not to require
anybody to dive into the source to confirm this )

### CODE REVIEW

**Comment by michaelklishin** [comment]
@binarin please submit the same against the `live` branch, too. Thank you!

**Comment by binarin** [comment]
Should it be cherry-picked to `live` or it should be done some other way?

**Comment by michaelklishin** [comment]
@binarin doesn't matter, whichever you prefer.

**Comment by michaelklishin** [comment]
@binarin in fact, nevermind, I'll do the cherry-picking.

**Pull request merged**
