### PR TITLE
Generated config and schema directory locations

### PR DESCRIPTION
**Pull request by almorelle**
@rsquelbut

### CODE REVIEW

**Comment by michaelklishin** [comment]
Who are we documenting this for? The average user doesn't care one bit about how the new style config works or combined with the advanced one.

The only scenario I can think of is when a generic UNIX package is used and every directory is overridden but then you might as well override `RABBITMQ_BASE` and be done with it.

So what problem are we solving here? Sorry but "we want every value to be listed" is a weak argument in this case.

**Comment by almorelle** [comment]
I understand and I agree but it turns out that's exactly what happened. We're using the generic UNIX package to install rabbitmq but we need to have rabbitmq base somewhere else. We did set `RABBITMQ_BASE` but rabbitmq still tries to write schema and generated config to rabbitmq system installation directory anyway.

While searching around for a while and after redefining every variable documented here, I found out about the following ticket and the rabbitmq-defaults.

https://github.com/rabbitmq/rabbitmq-server/issues/750
(also 751 and 752)

https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-defaults

Anyway, I agree and I suppose there might be an issue with these two operations (generating config and writing schemas) not supporting `RABBITMQ_BASE`.

Also sorry for the small descriptions, I'm not familiar with rabbitmq.

**Comment by michaelklishin** [comment]
If those two variables do not respect `RABBITMQ_BASE` and you can provide a way to reproduce it, please file a ticket with rabbitmq-server and we'll if they can (we depend on an external tool for config validation and generation).

**Comment by lukebakken** [comment]
@almorelle - `RABBITMQ_BASE` is a Windows-only environment variable. I'm assuming this was not made clear enough in our documentation [here](https://www.rabbitmq.com/relocate.html#locations) but it is mentioned [here](https://www.rabbitmq.com/relocate.html#unix). I will update that page.

**Pull request merged**
