### PR TITLE
Example syntax fix; added missing comma

### PR DESCRIPTION
**Pull request by afd3dea**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@afd3dea Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=747)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=747) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
The code works for me on Go 1.11 as is. Why is this change necessary?

**Comment by afd3dea** [comment]
Total newbie when it comes to go, but I received the following error when trying without the ending comma. It was my impression that either you have to have the closing parenthesis or a comma.

```
/ # go version
go version go1.11.5 linux/amd64

/ # go run test.go
# command-line-arguments
/test.go:84:6: syntax error: unexpected newline, expecting comma or )
```

With comma works perfectly.

**Comment by michaelklishin** [comment]
But there is a closing parenthesis to `ch.QueueBind(` in the [live version](https://www.rabbitmq.com/tutorials/tutorial-three-go.html). I've asked someone else to take a nother look in case I'm missing something but this seems to be a problem with your local file, not the website or [executable tutorial version](https://github.com/rabbitmq/rabbitmq-tutorials/tree/master/go).

Thank you for taking the time to contribute, though! 👍

**Comment by afd3dea** [comment]
Ah, right - I'm looking at the example in the text flow (Ctrl+F "between exchange"), which is where I thought I was comitting to.

Screenshot: https://imgur.com/a/ECdn5oY

from https://www.rabbitmq.com/tutorials/tutorial-three-go.html

**Comment by gerhard** [comment]
Invalid syntax because `unexpected newline, expecting comma or )`

image

Valid syntax:

image

**Comment by michaelklishin** [comment]
I see now, I was comparing it to

``` go
	err = ch.QueueBind(
		q.Name, // queue name
		"",     // routing key
		"logs", // exchange
		false,
		nil)
```

in the version that I tried. Thanks @afd3dea and @gerhard (who also has applied this change manually).

**Pull request closed without merging**
