### PR TITLE
Fix typo on access-control.xml

### PR DESCRIPTION
**Pull request by antonioalmeida**
Obvious fix.

Replace ```and but``` with ```and``` on 

> "use LDAP backend for authentication **and but** internal backend for authorisation"

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@antonioalmeida Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=675)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=675) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@antonioalmeida This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
Good catch. Thank you!

**Comment by lukebakken** [comment]
PS I was going to add the following to this PR but you beat me to it: 901aba3

**Pull request merged**
