### PR TITLE
Add link to rabtap cli tool

### PR DESCRIPTION
**Pull request by jandelgado**
I've added a link to the rabtap tool (RabbitMQ wire tap and swiss army knife; https://github.com/jandelgado/rabtap)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jandelgado Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=565)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=565) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jandelgado Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=565)!

**Comment by michaelklishin** [comment]
Thank you for contributing. We usually add tools to that guide once they gain some traction in the community. We are not entirely sure how to proceed since the tool does seem to be well maintained and documented but none of our team members have heard of it.

It will take some time for us to reach consensus on whether we can merge this.

**Comment by michaelklishin** [comment]
After spending some time with `rabtap` I think it does cover a few areas that no CLI tools currently can (although rabbitmq-tracing provides some of the same features). I think it is worth listing 👍

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
