### PR TITLE
Update ttl.md - correct value for C# expiration

### PR DESCRIPTION
**Pull request by BreadTh**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@BreadTh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1146)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1146) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@BreadTh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1146)!

**Comment by BreadTh** [comment]
I'm not sure what the old value is, but the value should clearly be 60000 miliseconds given the above 60 second definition.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
