### PR TITLE
[Fix-502] Update "smart" quotes to plain quotes on rabbitmqctl page for code examples

### LINKED ISSUE #502: Plain-ascii double quotes should be preferred
On [this page](https://www.rabbitmq.com/rabbitmqctl.8.html), "smart" quotes are used in the `rabbitmqctl` command examples rather than ascii double quotes. This could cause issues if someone copies and pastes from the page.

### PR DESCRIPTION
**Pull request by rallytime**
This change helps people with copy/pasting code examples directly from the page.

Fixes #502

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rallytime Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=825)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=825) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rallytime Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=825)!

**Comment by lukebakken** [comment]
@rallytime - thanks a lot for using RabbitMQ and taking the time to update this.

The `.html` files that contain smart quotes are actually generated from [this source](https://github.com/rabbitmq/rabbitmq-server/tree/master/docs) by [this `make` target](https://github.com/rabbitmq/rabbitmq-server/blob/master/Makefile#L271-L293). So, if there is a way to tell `mandoc` to not output "curly quotes" for HTML documents, that would be ideal. Otherwise, that `awk` program could be modified to replace curly quotes with `&quot;`.

I suspect when I opened #502 I didn't know how the `.html` documents were generated.

**Comment by rallytime** [comment]
Fair enough. :smile:

Is that documented anywhere? I had a suspicion that those files would be auto-generated, but I checked a couple of commits in that file and it looked like people were directly changing it and I didn't see a mention of how these were built anywhere. (Though I certainly could have missed it looking around here - I only looked briefly.)

**Comment by lukebakken** [comment]
There is the following README: https://github.com/rabbitmq/rabbitmq-website/tree/live/site/man

**Comment by rallytime** [comment]
Thanks for the pointers!

**Pull request closed without merging**
