### PR TITLE
Add more details for the HA OCF resource creation

### PR DESCRIPTION
**Pull request by bogdando**
* Provide precise example commands to create multi-state resource
for the RabbitMQ HA resource agent in Pacemaker.
* Provide the example commands in both pcs and crm tools notations.
* Describe the way to get meta-data parameters of the
OCF scripts via the command line (just to not duplicate
maintaning them in the guide and the script ot once)

Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by bogdando** [comment]
Thank you too. I wrote these docbook stanzas on a fly, have no idea how to verify build. I hope the syntax was OK :)

**Comment by michaelklishin** [comment]
@bogdando see README. Should be as easy as installing a few Python packager, running `localhost:8191` and navigating to `http://localhost:8191/pacemaker.html`.

**Comment by bogdando** [comment]
Thanks. The build looks correct, checked it out :)

**Pull request merged**
