### PR TITLE
Caveat about unsupported priority queue conversion

### PR DESCRIPTION
**Pull request by johanrhodin**
As per https://groups.google.com/d/msg/rabbitmq-users/Dpl6uR3-LYQ/QSqB4qI7BgAJ priority queue migration is currently unsupported

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@johanrhodin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=881)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=881) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
Thank you. I will push a different wording later today.

**Comment by johanrhodin** [comment]
OK, or let me know which type of formulation you want. I guess the work is the same, but would be happy to re-word if necessary.

**Comment by michaelklishin** [comment]
This has not been forgotten.

**Pull request closed without merging**
