### PR TITLE
Document two 'new' features: channel_max_per_node and consumer_max_per_channel

### PR DESCRIPTION
**Pull request by johanrhodin**
These were added to the server in https://github.com/rabbitmq/rabbitmq-server/commit/d7374cb244af961331f24e060e77f721edb2b6d1 but never documented.

### CODE REVIEW

**Comment by michaelklishin** [comment]
This only updates the 4.0 version of the site.

**Comment by michaelklishin** [comment]
This feature was backported to 3.13 in https://github.com/rabbitmq/rabbitmq-server/pull/10755 but this PR only updates the 4.0 version of the docs.

**Comment by johanrhodin** [comment]
...even 3.12.14 according to release notes https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.12.14

**Comment by michaelklishin** [comment]
Thank you.

**Pull request merged**
