### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hashlash**
Fix typo from "wueue" to "queue" in Queue Durability section.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hashlash Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=988)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=988) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by hashlash** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@hashlash This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
Thank you!

**Comment by hashlash** [comment]
Your welcome :+1:

**Pull request merged**
