### PR TITLE
Make site preview work on macOS 10.14.6

### PR DESCRIPTION
**Pull request by gerhard**
This fixes it for me, but rather than pushing it and breaking it for others, it would help to have the team members that run it locally confirm that it still works for them after this change.

### CODE REVIEW

**Comment by michaelklishin** [comment]
This fails on 12.0 beta with

```
✘ Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
[pipenv.exceptions.VirtualenvCreationException]:       return f(get_current_context(), *args, **kwargs)
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.8/site-packages/pipenv/cli/command.py", line 202, in cli
[pipenv.exceptions.VirtualenvCreationException]:       ensure_project(
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 570, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       ensure_virtualenv(
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 505, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       do_create_virtualenv(
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 934, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       raise exceptions.VirtualenvCreationException(
[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/virtualenv.py", line 2634, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/virtualenv.py", line 860, in main
    create_environment(
  File "/usr/local/lib/python3.8/site-packages/virtualenv.py", line 1162, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/usr/local/lib/python3.8/site-packages/virtualenv.py", line 1451, in install_python
    copy_required_modules(home_dir, symlink)
  File "/usr/local/lib/python3.8/site-packages/virtualenv.py", line 1341, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "/usr/local/lib/python3.8/site-packages/virtualenv.py", line 1273, in change_prefix
    raise AssertionError("Filename {} does not start with any of these prefixes: {}".format(filename, prefixes))
AssertionError: Filename /usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py does not start with any of these prefixes: ['/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Extras/lib/python', '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9', '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9', '/Users/antares/Library/Python/3.9/lib/python/site-packages', '/Users/antares/.local/lib/python/3.9/site-packages', '/Users/antares/Library/Python/3.9/site-packages', '/Library/Python/3.9/site-packages']
```

**Comment by michaelklishin** [comment]
`python3` in `PATH` is a very long standing convention, can we assume that `3` as a VirtualEnv version name would also work? Nothing in this repo really requires 3.9.

**Review by Zerpet — COMMENTED** [review]
Works for me in macOS 11.6 ✅

**Comment by gerhard** [comment]
How about now @michaelklishin?

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
I only have access to 11.6 right now but let's merge this. I can always run `./driver.py` directly with any Python 3 installation on 12.0 betas.

**Pull request merged**
