### PR TITLE
Fixed 'durable' typo in tutorial-two-javascript.md code snippet

### PR DESCRIPTION
**Pull request by spikers**
Changed a code snippet from `durable: true` to `durable: false`, where `durable: true` gives an 'inequivalent arg' error when the code is run and `durable: false` queues the message correctly.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@spikers Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=456)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=456) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@spikers Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=456)!

**Comment by michaelklishin** [comment]
Thank you but this is

**Comment by spikers** [comment]
Thank you for your time. I agree with you that the rest of the tutorial uses the durable one. 

Would you accept a suggestion where, instead of the first task_queue.js snippet changing, the first worker.js snippet is clarified from:
```
ch.consume(q, function(msg) {
  var secs = msg.content.toString().split('.').length - 1;

  console.log(" [x] Received %s", msg.content.toString());
  setTimeout(function() {
    console.log(" [x] Done");
  }, secs * 1000);
}, {noAck: true});
```
to
```
var q = 'task_queue';

ch.assertQueue(q, {durable: true});
console.log(" [*] Waiting for messages in %s. To exit press CTRL+C", q);
ch.consume(q, function(msg) {
  var secs = msg.content.toString().split('.').length - 1;

  console.log(" [x] Received %s", msg.content.toString());
  setTimeout(function() {
    console.log(" [x] Done");
  }, secs * 1000);
}, {noAck: true});
```
This shows the worker.js explicitly asserting task_queue as durable. 

I only mention this because when I went through the tutorials last week, I changed the requested lines of code, but I left worker.js to assert the task_queue queue as not-durable (This was carry-over from the previous tutorial). 

Later in the tutorial, worker.js is run FIRST, so the queue is initially asserted as not-durable. When new_task.js is run, it gives the inequivalent arg 'durable' error.

**Pull request closed without merging**
