### PR TITLE
Configuration guide: more readable multi-column tables

### PR DESCRIPTION
**Pull request by michaelklishin**
Based on and supersedes #846.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@lukebakken ready for another round.

**Comment by michaelklishin** [comment]
@gerhard and I agreed to switch all tables to be 2 columns, with defaults being the bottom part of the Description column.

**Comment by lukebakken** [comment]
I just checked on OS X using rabbitmq.com/configuration.html - looks great 👍

**Comment by gerhard** [comment]
Good improvement 👍

**Pull request merged**
