### PR TITLE
Update install-windows.md

### PR DESCRIPTION
**Pull request by cseas**
Grammar fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cseas Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=905)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=905) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by cseas** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@cseas This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
