### PR TITLE
Removed line numbers from tutorial-six-python.md

### PR DESCRIPTION
**Pull request by Clivern**
It would be better to just have a general explanation like other guides without these line numbers. it seems website code highlighter doesn't support line numbers.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Clivern Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1038)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1038) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Clivern Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=1038)!

**Review by michaelklishin — APPROVED** [review]
I agree

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
