### PR TITLE
[docs] DLX minor typo

### PR DESCRIPTION
**Pull request by mhujer**
Obvious Fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mhujer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=770)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=770) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mhujer** [comment]
IMO CLA is not required as this falls under _[Obvious fixes](https://cla.pivotal.io/about#obvious-fixes)_.

**Comment by pivotal-issuemaster** [comment]
@mhujer This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by michaelklishin** [comment]
That's an eager regex find-and-replace artifact. Thank you!

**Pull request merged**
