### PR TITLE
Swap in RabbitMQ call for papers banner

### PR DESCRIPTION
**Pull request by jesse-martinez**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jesse-martinez Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=736)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-website&pullRequestId=736) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
@jesse-martinez thank you!

**Comment by michaelklishin** [comment]
@jesse-martinez not sure why the live version has the rabbit image skewed to the right, perhaps some resources haven't yet propagated through the CDN?

**Comment by michaelklishin** [comment]
It is fine now.

**Pull request merged**
